/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary': '#ffffff',
        'background': '#fcf9f8',
        'surface-tint': '#a04100',
        'on-primary-fixed': '#351000',
        'on-error-container': '#93000a',
        'on-secondary-container': '#6f5c00',
        'primary-fixed-dim': '#ffb693',
        'on-error': '#ffffff',
        'inverse-on-surface': '#f3f0ef',
        'surface-variant': '#e5e2e1',
        'inverse-primary': '#ffb693',
        'surface-container-high': '#eae7e7',
        'on-background': '#1c1b1b',
        'inverse-surface': '#313030',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#ffdbcc',
        'secondary-container': '#fdd400',
        'error': '#ba1a1a',
        'surface': '#fcf9f8',
        'on-primary-container': '#572000',
        'tertiary': '#5f5e5e',
        'on-secondary-fixed': '#221b00',
        'on-secondary': '#ffffff',
        'primary': '#a04100',
        'surface-bright': '#fcf9f8',
        'on-surface-variant': '#5a4136',
        'outline': '#8e7164',
        'surface-dim': '#dcd9d9',
        'primary-container': '#ff6b00',
        'on-tertiary-container': '#313131',
        'surface-container-highest': '#e5e2e1',
        'tertiary-container': '#9a9898',
        'on-primary-fixed-variant': '#7a3000',
        'surface-container-low': '#f6f3f2',
        'on-secondary-fixed-variant': '#544600',
        'secondary': '#705d00',
        'error-container': '#ffdad6',
        'secondary-fixed-dim': '#e9c400',
        'surface-container': '#f0eded',
        'secondary-fixed': '#ffe170',
        'on-surface': '#1c1b1b',
        'on-tertiary': '#ffffff',
        'outline-variant': '#e2bfb0',
        /* dark overrides (applied via .dark class) */
        'dark-surface': '#1a1a1a',
        'dark-primary': '#ff6b00',
      },
      fontFamily: {
        headline: ['"Barlow Condensed"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '1rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
